### ISSUE TITLE
Only one dropdown alert displayed at a time

### ISSUE THREAD

**Issue by jaredreich** [cwRichardKim/RKDropdownAlert#10]
Hello, what do you think about implementing an event listener for if the user touches anywhere outside of the dropdown. For example to prevent overlapping of multiple dropdowns if the user presses a button somewhere on the screen that triggers a new dropdown (they could potentially have tons of dropdowns displaying on the screen if the delay was long enough).

Thanks for reading!

- Jared

**Comment by cwRichardKim** [comment]
shouldn't be too difficult, I'll keep this open until I have some time to build it.  If you have the time, feel free to try!

**Comment by jaredreich** [comment]
I think the better solution might actually be to allow only one dropdown alert at a time. Like for example if one is showing but still has 5 seconds left, and another one is initiated, then the first one will ignore it's remaining timer, close out with it's normal close animation (slides back up), then the new one will present. What do you think? I'd be glad to try this myself, I'm very new to Git/GitHub though so we'll see how I do. I can try making a pull request if you agree with this thought.

**Comment by clsource** [comment]
I solved this issue by calling [RKDropdownAlert dissmissAllAlert] before showing an alert.

**Comment by jaredreich** [comment]
Nice, thanks.
