### ISSUE TITLE
Feature Request: Custom font

### ISSUE THREAD

**Issue by MacieHummer** [cwRichardKim/RKDropdownAlert#16]
I like that I can customize the alert with a custom background color and text color... but I would also like to be able to give it a custom font. Thanks! :)

**Comment by cwRichardKim** [comment]
unfortunately the repo methods get pretty lengthy at that point =/ it's a poor design choice on my side to try to make everything work on one line, but unfortunately that's what we have to work with.  If you want to change the fonts yourself, it's really easy to just jump into the code and do so!

You'd want to add it on this line:
-(void)title:(NSString*)title message:(NSString*)message backgroundColor:(UIColor*)backgroundColor textColor:(UIColor*)textColor time:(NSInteger)seconds

just set the font of the titleLabel or messageLabel
