### ISSUE TITLE
Autoresize with on interface orientation

### ISSUE THREAD

**Issue by karmeye** [cwRichardKim/RKDropdownAlert#17]
If the device is in portrait and the orientation is changed to landscape while the alert is displayed the view is not resized to fit the whole width.

**Comment by LindyLo** [comment]
Just add 

        self.autoresizingMask = UIViewAutoresizingFlexibleWidth;

to - (id)initWithFrame:(CGRect)frame  in RKDropdownAlert.m

additionally add constrains to Labels (after [view addSubview]):

    titleLabel.translatesAutoresizingMaskIntoConstraints = NO;
        messageLabel.translatesAutoresizingMaskIntoConstraints = NO;
        
        [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|-[titleLabel]-|"  options:0 metrics:nil views:NSDictionaryOfVariableBindings(titleLabel)]];
        [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|-[messageLabel]-|"  options:0 metrics:nil views:NSDictionaryOfVariableBindings(messageLabel)]];
        
        
        [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-top_spacing-[titleLabel]-bottom_spacing-[messageLabel]-(>=8)-|"
                                                                   options:0
                                                                     metrics:@{@"top_spacing":@30.0,@"bottom_spacing":@10.0}
                                                                       views:NSDictionaryOfVariableBindings(titleLabel,messageLabel)]
         ];
