### ISSUE TITLE
dropdownAlertWasTapped always called

### ISSUE THREAD

**Issue by Tibb** [cwRichardKim/RKDropdownAlert#23]
Hi,
Thx for this lib, really clean and helpful!

I'm just facing an issue..
I've set an alert that looks like this:

`[RKDropdownAlert title:@"Notification" message:@"Message" backgroundColor:[UIColor grayColor] textColor:[UIColor whiteColor] time:5 delegate:self];`

and implemented the delegate's method like that:

`- (BOOL)dropdownAlertWasTapped:(RKDropdownAlert *)alert{
    [self doSomething];
    return YES;
}`

`- (BOOL)dropdownAlertWasDismissed{
    return YES;
}`

My problem is: `dropdownAlertWasTapped` is always called after the 5 seconds time, even when I'm not touching the screen.

**Comment by OskarZhang** [comment]
I did a quick fix and you can find it in my fork of this repo here:  https://github.com/OskarZhang/RKDropdownAlert :)
