### ISSUE TITLE
wrong cocoapod

### ISSUE THREAD

**Issue by lunarbase** [cwRichardKim/RKDropdownAlert#8]
your cocoapod spec on cocoapod.org is downloading RKNotificationHub that is a code that has nothing to do with notifications.

**Comment by cwRichardKim** [comment]
interesting, i'll look into it. i just double checked my podspec and it looks ok on my side

**Comment by cwRichardKim** [comment]
oh i found the issue. thanks for letting me know! i'm updating it now
